import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    // default:"This is Meta testing",
    template:"%s | Testing the template",

  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

        {/* <header>Header</header> */}
      <body>
        {children}
      </body>
        {/* <footer>Footer</footer> */}
    </html>
  );
}
